version: "3.9"

services:
  mcp:
    build: .
    #restart: always
    env_file:
      - .env
    environment:
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_CHANNEL_ID: ${SLACK_CHANNEL_ID}
      SUPABASE_DB_URL: ${SUPABASE_DB_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
